# Default values for theia.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

app:
  name: 'pignus-api'
  debug: False
  database:
    host: " mysql-dev.pignus-dev.svc.cluster.local"
    name: "pignus_1"



image:
  repository: "docker.io"
  tag: "latest"
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}

podSecurityContext: {}

securityContext: {}

resources: {}
