# Default values for theia.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
fullname: "pignus-api"

app:
  debug: False
  database:
    host: "mysql.local"
    port: 3306
    name: "pignus"

image:
  repository: "docker.io"
  tag: "latest"
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}

podSecurityContext: {}

securityContext: {}

resources: {}
