#!/bin/sh -l
# Pignus Build

set -e
echo "Running Pignus Build"

echo "Removing Pignus"
rm -rf /usr/local/lib/python3.9/site-packages/pignus-0.0.*
rm -rf /app/build
rm -rf /app/dist
rm -rf /app/pignus.egg-info

echo "Building Pignus"
cd /app
python3 setup.py build
python3 setup.py install


cd /app
flake8

echo "Running tests"
cd /tests/unit
pytest --cov=pignus_api --cov=pignus_client
