{{- if .Values.pignus_sentry.debug }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pignus-sentry.fullname" . }}
  labels:
    {{- include "pignus-sentry.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "pignus-sentry.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "pignus-sentry.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "pignus-sentry.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: "{{ .Chart.Name }}-sentry"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.pignus_sentry.image.repository }}:{{ .Values.pignus_sentry.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.pignus_sentry.image.pullPolicy }}
          {{- if .Values.pignus_sentry.debug }}
          command: ['sh', '-c', 'tail -f /dev/null']
          {{- end }}
          env:
          - name: PIGNUS_API_URL
            valueFrom:
              configMapKeyRef:
                name: pignus-sentry
                key: api_url
          - name: PIGNUS_API_KEY
            valueFrom:
              secretKeyRef:
                name: "pignus-sentry"
                key:  "api_key"
          - name: PIGNUS_API_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: "pignus-sentry"
                key:  "client_id"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}