apiVersion: v1
kind: Service
metadata:
  name: {{ include "pignus-api.fullname" . }}
  labels:
    {{- include "pignus-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5001
      protocol: TCP
      name: http
  selector:
    {{- include "pignus-api.selectorLabels" . | nindent 4 }}
