apiVersion: v1
kind: ConfigMap
metadata:
  name: pignus
data:
  pignus_theia_kube_api: "https://kubernetes.default.svc"
  pignus_theia_cluster: "{{ .Values.app.pignus.cluster }}"
  pignus_api_ua: "Cluster-{{ .Values.app.pignus.cluster }}"
  pignus_api_url: "{{ .Values.app.pignus.apiUrl }}"
