# Pignus Docker Pignus-API
# This workflow builds the container, politeauthority/pignus-api

name: Docker Pignus-Api

on:
  push:
    branches: [ "main", "develop", "cicd" ]
  pull_request:
    branches: [ "main", "develop", "cicd"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      # -
      #   name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
      #     password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./docker/pignus-api/
          file: ./docker/pignus-api/Dockerfile
          # push: true
          tags: politeauthority/pignus-api:0.0.1
