# Pignus Docker Pignus-API
# This workflow builds the container, politeauthority/pignus-api

name: Docker Pignus-Api

on:
  push:
    branches: [ "main", "develop", "cicd" ]
  pull_request:
    branches: [ "main", "develop", "cicd"]

jobs:
  build:
    runs-on: self-hosted
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3

      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      -
        name: Copy Files
        run: |
          cp -r ./src ./docker/pignus-api

      -
        name: Build Container
        run: |
          cd ./docker/pignus-api/
          docker build . -t politeauthority/pignus-api:0.0.2-${{ github.ref_name }}

      -
        name: Push Container
        run: |
          docker push politeauthority/pignus-api:0.0.2-${{ github.ref_name }}
