# Pignus Regression


---

name: Pignus-Regression

on:
  push:
    branches: "regression-test"

jobs:
  run-regression:
    runs-on: self-hosted
    container:
      image: politeauthority/pignus-test:latest
      env:
        PIGNUS_API_URL: "${{ secrets.REGRESSION_PIGNUS_API_URL }}"
        PIGNUS_API_CLIENT_ID: "${{ secrets.REGRESSION_PIGNUS_API_CLIENT_ID }}"
        PIGNUS_API_KEY: "${{ secrets.REGRESSION_PIGNUS_API_KEY }}"
    steps:
      - name: Check for dockerenv file
        run: ls /tests

# End File: pignus/.github/workflows/pignus-regression.yaml
