# Pignus-Api Deploy Helm
# This workflow builds the container, politeauthority/pignus-api

name: Pignus-Api Regression
# on: ['deployment']
on:
  push:
    branches: [ "main", "staging", "helm-deploy" ]

jobs:
  deployment:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1

    - name: 'Deploy'
      uses: 'glopezep/helm@v1.7.1'
      with:
        release: 'pignus-cicd'
        namespace: 'pignus-cicd'
        chart: 'helm/pignus-api'
        helm: 'helm3'
        token: '${{ github.token }}'
        value-files: '["helm/pignus-api/values.yaml", "helm/pignus-api/values-regression.yaml"]'
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'

# .github/workflows/pignus-api-deploy-helm.yml
