# Pignus Api Test
# This workflow controls the following
# - Builds the Python Pignus package
# - Lints the Python Pignus package
# - Tests the Python Pignus package
# - Builds the Pignus-Api-Dev Docker container
# - Deploys the Pignus-Api-Dev container to the pignus-cicd K8s namespace
# - Runs the Pignus regression tests against the pignus-cicd K8s namespace

---

name: Pignus-Api-Test

on:
  pull_request:
    branches: "staging"

jobs:
  build-python:
    runs-on: self-hosted
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest
          pip install -r src/requirements-debug.txt
          pip install -r src/requirements.txt

      - name: Build Packages
        run: |
          cd src/
          python setup.py build
          python setup.py install

      - name: Linter
        run: |
          cd src/pignus_api
          flake8 . --count --show-source --statistics

      - name: Unit Tests
        run: pytest tests/unit/pignus_api

  build-docker:
    runs-on: self-hosted
    needs: build-python
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Container
        run: |
          echo "ALIX-DEBUG"
          echo "$(ls)"
          cp -r ./src ./docker/pignus-api-dev
          cp -r ./tests ./docker/pignus-api-dev
          cd ./docker/pignus-api-dev/
          docker build docker/pignus-api-dev/ -t politeauthority/pignus-api-dev:${{ github.sha }}

      - name: Push Container
        run: |
          docker push politeauthority/pignus-api-dev:${{ github.sha }}

  deploy-test:
    runs-on: self-hosted
    needs: build-docker
    container:
      image: politeauthority/pignus-cicd:latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v1
      - run: |
          cd helm/pigus-api
          helm install --upgrade pignus-cicd -f values.yaml -f values-regression.yaml
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'

  run-regression:
    runs-on: self-hosted
    needs: deploy-test
    container:
      image: politeauthority/pignus-api-dev:${{ github.sha }}
      env:
        PIGNUS_API_URL: "${{ secrets.REGRESSION_PIGNUS_API_URL }}"
        PIGNUS_API_CLIENT_ID: "${{ secrets.REGRESSION_PIGNUS_API_CLIENT_ID }}"
        PIGNUS_API_KEY: "${{ secrets.REGRESSION_PIGNUS_API_KEY }}"
    steps:
      - name: Regression Pignus-Api
        run: cd /tests/regression && pytest

# End File: pignus/.github/workflows/pignus-api-test.yaml
