# Pignus Python Package
# This workflow install dependencies, builds, lints and runs unit tests for the Pignus source.


name: Pignus-Api Package and Test

on:
  push:
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build-python:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        pip install -r src/requirements-debug.txt
        pip install -r src/requirements.txt

    - name: Linter
      run: |
        cd src/pignus_api
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Build Packages
      run: |
        cd src/
        python setup.py build
        python setup.py install

  build-docker:
    runs-on: self-hosted
    steps:
    - name: Build Container
      run: |
        cp -r ./src ./docker/pignus-api
        cd ./docker/pignus-api/
        docker build . -t politeauthority/pignus-api

  test-python:
    runs-on: self-hosted
    steps:
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        pip install -r src/requirements-debug.txt
        pip install -r src/requirements.txt

    - name: Unit Tests
      run: |
        pytest tests/unit/pignus_api


